name: GitHub Actions for Checking backports
on:
  push:
  schedule:
    # Run cron every 60 minutes
    - cron:  '0 */12 * * *'
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies, deposit secret
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir -p .secrets/
        echo "${{ secrets.SERVICE_ACCOUNT_JSON}}" | base64 --decode > .secrets/service_account.json
    - name: Run Script
      run: |
        python main.py
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@master
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1.2.1
